/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '16-8-30 下午2:59' with Gradle 3.0
 *
 * @author admin, @date 16-8-30 下午2:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
